flush ruleset;

table ip filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # baseline rules
        iifname "lo" accept;
        ct state established,related accept;
        ip protocol icmp accept;

        # blacklist
        ip saddr 192.0.2.1 drop

        # open ports
        tcp dport 8000 accept;
        tcp dport 8089 accept;
        tcp dport 9997 accept;
        tcp sport 9997 accept;

        # whitelisted ports
        # example: ip saddr 198.51.100.1 tcp dport 80 accept;
    }
}

