CREATE DATABASE IF NOT EXISTS Greyrose_DB;

--greyrose_user

GRANT ALL PRIVILEGES ON Greyrose_DB.* 
--granted_privileges
USE Greyrose_DB;

CREATE TABLE IF NOT EXISTS accepted_ports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT,
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_ports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT,
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS allowed_services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS allowed_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS whitelist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blacklist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO allowed_services (name)
VALUES ("Greyrose.service")