CREATE DATABASE IF NOT EXISTS Greyrose_DB;

CREATE USER IF NOT EXISTS 'greyrose_user'@'localhost'
IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON Greyrose_DB.* 
TO 'greyrose_user'@'localhost';

FLUSH PRIVILEGES;

USE Greyrose_DB;

CREATE TABLE IF NOT EXISTS accepted_ports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT,
    connection_type varchar(3),
    transmission_type varchar(5),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_ports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    port INT,
    connection_type varchar(3),
    transmission_type varchar(5),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS allowed_services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_services (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS allowed_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blocked_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS whitelist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blacklist (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(50),
    time_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
