#!/usr/bin/env python3

import subprocess
import logging
import mariadb

#connect with the mariadb database
try:
    conn = mariadb.connect(
        user="greyrose_user",
        password="password",
        host="127.0.0.1",
        port=3306,
        database=Greyrose_DB
    )
except mariadb.Error as e:
    print(f"error connecting to MariaDB: {e}")
    sys.exit(1)

cursor = conn.cursor()

accepted_ports = []
blocked_ports = []
allowed_services = []
blocked_services = []
allowed_users = []
blocked_users = []
whitelist = []
blacklist = []

def fetch():
    #use sql to fetch whitelist, and blacklist
    cursor.execute("SELECT port FROM accepted_ports")
    accepted_ports = [row for row in cursor.fetchall()]

    cursor.execute("SELECT port FROM blocked_ports")
    blocked_ports = [row for row in cursor.fetchall()]

    cursor.execute("SELECT name FROM allowed_services")
    allowed_services = [row for row in cursor.fetchall()]

    cursor.execute("SELECT name FROM blocked_services")
    blocked_services = [row for row in cursor.fetchall()]

    cursor.execute("SELECT name FROM allowed_users")
    allowed_users = [row for row in cursor.fetchall()]

    cursor.execute("SELECT name FROM blocked_users")
    blocked_users = [row for row in cursor.fetchall()]

    cursor.execute("SELECT ip FROM whitelist")
    whitelist = [row for row in cursor.fetchall()]

    cursor.execute("SELECT ip FROM blacklist")
    blacklist = [row for row in cursor.fetchall()]

operating_system = '^NAME=' + " /etc/os-release"
log_name = subprocess.run(["sudo", "grep", "-Po", operating_system])
#Centralized logging in ubuntu.log file
#logging.basicConfig(level=logging.DEBUG, filename=ubuntu.log, 
#    filemode="w", format="%(asctime)s - %(levelname)s - %(message)s")

#function to reload table after configuration file change
def reload():
    subprocess.run(["sudo", "nft", "-f", "nftables.conf"])

#function to add to mariadb database
def add_to_db(table, value, index):
    query = f"INSERT INTO {table} (id, {index}, time_added) VALUES (?, ?, ?)"
    cursor.execute(query, (f"DEFAULT", {value}, DEFAULT))
    conn.commit()

#funciton to remove from mariadb database
def remove_from_db(table, value, index):
    query = f"DELETE FROM {table}, WHERE {index} = ?"
    cursor.execute(query, value)
    conn.commit()

#function to add port
def add_port():
    port_number = input("Port Number: ")
    if port_number in accepted_ports:
        print("port already accepted")
        return
    if port_number in blocked_ports:
        remove_from_db("blocked_ports", port_number, "port")
    string_arg = f'/# END: ACCEPTED INSIDE PORT CONNECTION/i \\\ttcp dport {port_number} accept'
    subprocess.run(["sudo", "sed", "-i",
        string_arg, "nftables.conf"])
    add_to_db("accepted_ports", port_number, "port")

#function to remove port
def remove_port():
    port_number = input("Port Number: ")
    if port_number in blocked_ports:
        print("port already blocked")
        return
    if port_number in accepted_ports:
        remove_from_db("accepted_ports", port_number, "port")
    string_arg = f'/# END: DENIED INSIDE PORT CONNECTIONS/i \\\ttcp dport {port_number} accept'
    subprocess.run(["sudo", "sed", "-i",
        string_arg, "nftables.conf"])
    add_to_db("blocked_ports", port_number, "port")

#function to add ip address
def add_ip():
    ip_address = input("ip address: ")
    if ip_address in whitelist:
        print("ip address is already accepted")
        return
    if ip_address in blacklist:
        remove_from_db("blacklist", ip_address, "ip")
    string_arg = f'/# END: ACCEPTED INSIDE IP CONNECTIONS/i \\\ttcp dport {ip_address} accept'
    subprocess.run(["sudo", "sed", "-i",
        string_arg, "nftables.conf"])
    add_to_db("whitelist", ip_address, "ip")

#function to add remove ip_address
def remove_ip():
    ip_address = input("ip address: ")
    if ip_address in blacklist:
        print("ip address is already blocked")
        return
    if ip_address in whitelist:
        remove_from_db("whitelist", ip_address, "ip")
    string_arg = f'/# END: ACCEPTED INSIDE IP CONNECTIONS/i \\\ttcp dport {ip_address} accept'
    subprocess.run(["sudo", "sed", "-i",
        string_arg, "nftables.conf"])
    add_to_db("blacklist", ip_address, "ip")

#function to add remove users
def add_user():
    user = input("name of user: ")
    if user in allowed_users:
        print("user is already on the whitelist")
        return
    if user in blocked_users:
        remove_from_db("blocked_users", user, "name")
    add_to_db("allowed_users", user, "name")

#function to remove users
def remove_user():
    user = input("name of user: ")
    if user in blocked_users:
        print("user is already blocked")
        return
    if user in allowed_users:
        remove_from_db("allowed_users", user, "name")
    add_to_db("blocked_users", user, "name")

#function to add service
def add_service():
    service = input("name of service: ")
    if service in allowed_services:
        print("service is already blocked")
        return
    if user in blocked_services:
        remove_from_db("blocked_services", service, "name")
    add_to_db("allowed_services", service, "name")

#function to remove service
def remove_service():
    service = input("name of service: ")
    if service in blocked_services:
        print("service is already blocked")
        return
    if service in allowed_services:
        remove_from_db("allowed_services", service, "name")
    add_to_db("blocked_services", service, "name")

#interactive interface for administrator
def interface():
    while True:
        functions = ["0. allow port through network", "1. blocked port"
                    "2. allow service to run on network", "3. block service"
                    "4. add ip to whitelist", "5. add ip to blacklist",
                    "6. allow new user on network", "7. block user on network"]

        for i in functions:
            print(i)
        
        choice = input("Choose function (enter number): ")

        functions = [add_port, block_port,
                    allow_service, blocked_services,
                    add_ip, remove_ip,
                    add_user, remove_user]

        functions[choice]()

        
fetch()
interface()