#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0;
        policy drop;

        # START: LOCAL CONNECTION
        iif "lo" accept
	# END: LOCAL CONNECTION

        # START: ACCEPTED INSIDE PORT CONNECTIONS
	tcp dport 80 accept
	tcp dport 443 accept
    tcp dport 9997 accept
	# END: ACCEPTED INSIDE PORT CONNECTION

	# START: DENIED INSIDE PORT CONNECTIONS
	tcp dport 22 drop
	# END: DENIED INSIDE PORT CONNECTIONS

	# START: ACCEPTED INSIDE IP CONNECTIONS
	
	# END: ACCEPTED INSIDE IP CONNECTIONS

	# START: DENIED INSIDE IP CONNECTIONS

	# END : DENIED INSIDE IP CONNECTIONS

        # START: ICMP/ICMPv6 CONNECTION
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept
	# END: ICMP/ICMPv6 CONNECTION
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
